Feat/#3/로그인 회원가입 api 연결
Leets-Official/Xcellent-FE pull request #4
Opened 2024-10-09 14:08 UTC by dalzzy

## 1. 무슨 이유로 코드를 변경했나요?
- 자체 회원가입 로그인 api 연결

<br>

## 2. 어떤 위험이나 장애를 발견했나요? 
- next-auth로 회원가입, 로그인을 구현하다가 사용하지 않는 것이 좋다고 하여 fetch만 사용하여 요청하는 방식으로 변경 
- next auth로 계속 시도하다가 급하게 변경하여 회원가입 에러를 아직 해결하지 못했습니다..

<br>
## 2. 관련 스크린샷을 첨부해주세요.

![image](https://github.com/user-attachments/assets/d15cfbed-0346-41a7-a651-1a186ccd3d57)

![image](https://github.com/user-attachments/assets/c1fac348-1662-4b4a-872d-7a660a3c6bf7)

<br>

## 3. 완료 사항
- 첫 화면 UI 
<br>

## 4. 추가 사항
- 오류 해결하여 회원가입 , 로그인 api 연결 완성할 예정입니다.. 
- 회원가입, 로그인 모달 ui도 구현할 예정입니다..
-
<br>

2024-10-09 15:02 UTC, yezzan9 commented on .env
> +NEXT_PUBLIC_BASE_URL=http://43.202.182.121:8080
👁️👁️
💧💧

2024-10-09 15:02 UTC, yezzan9 commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
div label 태그가 이중으로 감싸져 있는데 의도하신 부분일까요?-?

2024-10-09 15:02 UTC, yezzan9 commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
아니면,, 이게 맞는 건데 label 태그 닫는 위치가 잘못된건가요?🧐

2024-10-09 15:02 UTC, yezzan9 commented on src/app/(route)/(beforeLogin)/_component/SignupModal.tsx
> +  const days = Array.from({ length: 31 }, (_, i) => i + 1);
31일까지 없는 달도 있으니 더 상세하게 설정해주면 좋을 것 같아요!

2024-10-09 15:02 UTC, yezzan9 commented on src/app/(route)/(beforeLogin)/_component/SignupModal.tsx
> +        </div>
`LoginModal`과 같습니다! 해당 파일 전반적으로 같은 상황인듯 하니 전부 확인해보면 좋을 것 같아요!

2024-10-10 06:49 UTC, One-HyeWon requested changes

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/@modal/(.)i/flow/login/page.tsx
> +  );
로그인 모달 컴포넌트만 반환 해줄 거라면 
`return <LoginModal />`로만 작성 해주셔도 됩니다!

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +  const [message, setMessage] = useState('');
세 변수 모두 이 컴포넌트 내에서만 상태 관리를 하게 된다면, email, password, message를 하나의 객체로 묶어 하나의 useState문으로 처리 가능 하게 할 수 있습니다!

```
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    message: ''
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // formData를 사용해서 로그인 처리
    console.log('Email:', formData.email);
    console.log('Password:', formData.password);
    console.log('Message:', formData.message);
  };
```

이런식으로 한 객체로 관리 할 수 있습니다!

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
Button 태그를 div로 한 번 더 감싸신 이유가 있으실까요?

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/_component/SignupModal.tsx
현재 파일에서 div 태그 안에 label과 input이 존재 하는 요소들과 select 태그들이 반복적으로 사용 되고 있는데, 동일한 구조와 스타일을 가진 요소들이라면 하나의 컴포넌트로 만들어서 작업하시는 걸 권장드립니다!

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/login/_component/RedirectToLogin.tsx
만약 클라이언트 컴포넌트로 관리할 이유가 없다면, 서버 컴포넌트로 바로 리다이렉트 되게 코드를 수정 할 수 있습니다!

```
import { redirect } from 'next/navigation';

export default function RedirectToLogin() {
  // 서버 측에서 바로 리다이렉트
  redirect('/i/flow/login');
}
```

이렇게 되면, 굳이 페이지 렌더링을 기다리지 않고 서버측에서 리다이렉트 되기 때문에 사용자 경험이 올라갑니다!

2024-10-10 06:49 UTC, One-HyeWon commented on src/app/page.tsx
page.tsx 파일에는 컴포넌트들만 오는 것이 좋습니다! 태그들을 직접 넣어서 화면을 구성하기 보다는 컴포넌트로 작업 하셔서 컴포넌트를 호출 하는 식으로 page 컴포넌트를 구성하는 것을 권장드립니다!
유지보수 및 재사용성을 높이는 코드를 지향하면 좋을 것 같습니다

2024-10-14 08:05 UTC, dalzzy commented on .env
> +NEXT_PUBLIC_BASE_URL=http://43.202.182.121:8080
😭.. 도메인 변경하여 다시 수정할 예정입니다,,

2024-10-14 08:18 UTC, dalzzy commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
이 코드를 의도한 것이 맞습니다..! 그런데 저렇게 하니까 a form label must be associated with a control 이라는 eslint 오류가 떠서  </label>이 input태그를 감싸도록 해야 오류가 사라지길래.. 그렇게 수정했는데 이 코드에서 체크하는 것을 빠뜨린 것 같습니다,,

2024-10-14 08:21 UTC, dalzzy commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +  const [message, setMessage] = useState('');
아하 한 객체로 관리하는게 더 좋을 것 같네요! 반영하여 수정하도록 하겠습니다!

2024-10-14 08:27 UTC, dalzzy commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
엇 div 태그로 위 코드들이랑 형식을 통일하려고 했던 것 같은데 보통 button태그는 div 태그로 감쌀 필요가 없나요?..

2024-10-14 08:36 UTC, dalzzy commented on src/app/(route)/(beforeLogin)/_component/SignupModal.tsx
그 부분은 생각하지 못했던 것 같습니다 반영하여 수정하겠습니다!!

2024-10-14 08:39 UTC, dalzzy commented on src/app/(route)/(beforeLogin)/login/_component/RedirectToLogin.tsx
넵 그렇게 수정하도록 하겠습니다!

2024-10-15 13:20 UTC, One-HyeWon commented on src/app/(route)/(beforeLogin)/_component/LoginModal.tsx
> +          </div>
굳이 추가적인 스타일을 주고싶은 게 아니라면, button 태그 자체에도 스타일을 줄 수 있어서 제거하셔도 됩니다!

2024-11-03 09:56 UTC, merged