Feature/#4/홈페이지 UI
Leets-Official/Xcellent-FE pull request #6
Opened 2024-11-05 12:45 UTC by heyn2

## 1. 무슨 이유로 코드를 변경했나요?

<br>

## 2. 관련 스크린샷을 첨부해주세요.
![image](https://github.com/user-attachments/assets/fd2f67f0-03b1-43df-a0c3-7b46cb3b2df4)

![image](https://github.com/user-attachments/assets/d8d35adb-0da6-4955-ba14-9e80cd4b6520)
(게시글 모달에서 게시글 작성 후 게시물이 정렬되지 않는 문제 해결 필요)

<br>

## 3. 완료 사항
1. 홈페이지 레이아웃 구성
2. 사이드바에 네비게이션 링크 추가
3. 게시글 작성 버튼 및 모달 기능 구현
4. 사용자 프로필 정보 표시 기능 추가
<br>

## 4. 추가 사항
Xcellent-FE\src\app\(route)\(afterLogin)\home\PostModal.tsx 추가하여 게시글 모달 생성
<br>

2024-11-05 15:33 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/layout.tsx
>            </nav>
왼쪽 메뉴바는 프로필이나 채팅에서도 사용되는 공통 컴포넌트라서 컴포넌트를 재사용할 수 있도록 (afterLogin)/_component에  코드를 분리하는게 좋을 것 같습니다!

2024-11-05 15:33 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/layout.tsx
commit 단위를 좀 더 세분화해서 올려주시면 좋을 것 같습니다..!

2024-11-05 15:33 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/layout.tsx
> +        </div>
인터셉팅 라우트과 패러렐 라우트를 사용해서 모달을 구현하시면 실제 X의 url과 같이 구현이 가능합니다..! 저도 이 방식으로 모달 구현했어용

2024-11-05 15:34 UTC, yezzan9 requested changes

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
>              </ul>
스타일이 동일하게 반복되는 부분은 객체를 매핑하는 식으로 수정하면 좋을 것 같아요~!

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
>              </ul>
next.js는 a태그 대신 Link 태그를 사용하는 것이 좋습니다!

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
> +      )}
모달의 경우 별도의 컴포넌트로 분리하는 것이 가독성 및 유지보수 측면에서 유리합니다!
상단의 div태그 두개는 하나로 통합할 수 있을 것 같아요

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
newPost, newComment 상태는 약간 굳이,, 인 것 같습니다
해당 상태는 로컬에서 임시저장하는 것 같은데 x서비스에는 임시저장 상태로 데이터를 저장하는 기능만 존재합니다 !

showComments도 comments로 수정하면 좋을 것 같아요~🤗

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
> +  };
post, like, retweet, comment 부분은 백엔드와 dto 조율이 된 건가요?-?

2024-11-05 15:34 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
>    return (
컴포넌트 분리가 전혀 안 되어있는 것 같은데, 게시글 내용 입력 부분 / 트윗 등의 단위로 컴포넌트를 분리하는 편이 좋을 것 같습니다!

2024-11-05 15:40 UTC, yezzan9 requested changes
오류가 있어서 리뷰 다시 남겨드립니다 !

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
>              </ul>
스타일이 동일하게 반복되는 부분은 객체를 매핑하는 식으로 수정하면 좋을 것 같아요~!

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
>              </ul>
next.js는 a태그 대신 Link 태그를 사용하는 것이 좋습니다!

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/layout.tsx
> +        </div>
모달의 경우 별도의 컴포넌트로 분리하는 것이 가독성 및 유지보수 측면에서 유리합니다!
상단의 div태그 두개는 하나로 통합할 수 있을 것 같아요

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
> +  const textareaRef = useRef<HTMLTextAreaElement>(null);
newPost, newComment 상태는 약간 굳이,, 인 것 같습니다
해당 상태는 로컬에서 임시저장하는 것 같은데 x서비스에는 임시저장 상태로 데이터를 저장하는 기능만 존재합니다 !

showComments도 comments로 수정하면 좋을 것 같아요~🤗

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
> +  };
post, like, retweet, comment 부분은 백엔드와 dto 조율이 된 건가요?-?

2024-11-05 15:40 UTC, yezzan9 commented on src/app/(route)/(afterLogin)/home/page.tsx
> +    <div className="flex min-h-screen bg-black text-white">
컴포넌트 분리가 전혀 안 되어있는 것 같은데, 게시글 내용 입력 부분 / 트윗 등의 단위로 컴포넌트를 분리하는 편이 좋을 것 같습니다!

2024-11-05 15:46 UTC, yezzan9 commented
현재 PR에 첨부되어있는 스크린샷만 해도 UI가 x서비스와 많이 다르게 구현되어있어요😂
실제 x서비스의 UI를 더 꼼꼼하게 확인하신 후 수정 부탁드립니다!

<img width="605" alt="스크린샷 2024-11-05 오후 11 52 40" src="https://github.com/user-attachments/assets/ca6a77f5-4aea-4b5c-951f-2b4feb256cd1">
<img width="605" alt="스크린샷 2024-11-06 오전 12 42 12" src="https://github.com/user-attachments/assets/9bfab6b1-ae39-4eab-bd89-96de480d7eb5">
<img width="627" alt="스크린샷 2024-11-06 오전 12 43 35" src="https://github.com/user-attachments/assets/94af8672-d42d-4829-aa90-be34c14e94fe">

2024-11-05 15:50 UTC, yezzan9 commented
커밋 컨벤션이 지켜지지 않고 있어요🥲 팀 노션을 참고하여 커밋 컨벤션을 지켜주세요!
커밋 단위도 현재보다 더 잘게 나누는 걸 추천드립니다!

2024-11-06 03:13 UTC, dalzzy commented
예진님이 첨부해주신 사진에서 "추천" , "팔로우 중" 탭에서 "팔로우 중" 탭만 구현하시면 됩니다..! 이미 알고 계신지 모르겠지만 혹시나 해서,, 알려드립니당..

2024-11-06 03:39 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/page.tsx
>    const handleRetweet = (id: number) => {
![image](https://github.com/user-attachments/assets/f59f0d14-2ec3-416a-9669-92cee184cba6)
리트윗 버튼을 누를 때마다 내가 리트윗한 게시물이 아래에 뜨는 방식으로 구현이 된 것 같은데 의도하신걸까용?..  실제 X의 home에서는 리트윗한 게시물이 따로 나타나지 않고 리트윗한 다른 사람의 게시물만 표시되는 방식이 사용되고 있습니다!

2024-11-06 03:42 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/page.tsx
> +  };
![image](https://github.com/user-attachments/assets/f59f0d14-2ec3-416a-9669-92cee184cba6)
리트윗 버튼을 누를 때마다 내가 리트윗한 게시물이 아래에 뜨는 방식으로 구현이 된 것 같은데 의도하신걸까용?..  실제 X의 home에서는 리트윗한 게시물이 따로 나타나지 않고 리트윗한 다른 사람의 게시물만 표시되는 방식이 사용되고 있습니다!

2024-11-06 07:54 UTC, dalzzy commented on src/app/(route)/(afterLogin)/home/layout.tsx
>            </nav>
프로필을 클릭했을 때 /profile 이 아니라 const me = { id: "dahyeon" }; const <Link href={`/${me?.id}`}> 이런식으로 동적 경로를 사용하도록 수정부탁드립니다.. api 연결 전까지 임시적으로 설정해놓으면 될 것 같아요

2024-11-06 16:32 UTC, heyn2 commented on src/app/(route)/(afterLogin)/home/layout.tsx
>            </nav>
(afterLogin)\_component\Sidebar.tsx 만들어서 코드 분리 완료 했고,  두 번째 피드백 주신 부분에서 동적 경로 사용하도록 코드상에 반영 하였는데 여전히 프로필을 클릭하면 http://localhost:3000/profile 이런 경로로 나타납니다.. 자세한 내용은 pr로 올려보도록 하겠습니다..!

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/_component/Sidebar.tsx
> +          </svg>
만약 고정되는 이미지 / 로고라면, image 태그를 따로 사용 하시는것을 추천드립니다
Next는 최적화 된 내장 컴포넌트가 있어서 확인 해보시면 좋을 것 같아요!
그리고 image path들은 상수 파이로 관리 하시는 것을 추천 드립니다
constant 파일에 imagePath.ts를 만들어 이미지 / 아이콘 경로들을 추가해두고 불러와서 사용하는 것도 좋을 것 같아요!

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/_component/Sidebar.tsx
> +        </nav>
list 태그로 구현 하신 이유가 있으신가요?

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/home/PostModal.tsx
> +  const router = useRouter(); // 클라이언트에서만 사용할 수 있음
주석을 달아주신 것 처럼 use client는 client 단에서 모든 요소들이 렌더링 됩니다! 따라서 Next.js를 사용하는 가장 큰 이유인 SSR을 최대한 활용 하시려면, 'use client'는 최대한 컴포넌트 하나하나로 분리하여 사용해주시는 것이 좋아요!

지금처럼 하나의 파일에 렌더링 되어야 할 구성 요소들이 많다면, router.back을 사용하는 컴포넌트들은 따로 분류하여 만들어주신 후, 이 파일에서 Import 하여 사용 하시면 이 파일은 SSR이 가능해지니 다른 text들은 서버단에서 미리 렌더링 될 수 있습니다!

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/home/PostModal.tsx
> +  }
해당 구문을 추가해주신 이유가 있으실까요?

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/home/layout.tsx
> +                </svg>
위와 동일합니다

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/home/layout.tsx
> +            <div className="flex justify-between items-center mb-4">
컨테이너 역할을 하는 div들이 많으면, container 컴포넌트를 따로 만들어주시는 것도 좋을 것 같아요!
그러면 어느 div 태그가 어느 요소들을 담고 있는지 더 쉽게 알 수 있을 것 같습니다

2024-11-07 08:26 UTC, One-HyeWon commented on src/app/(route)/(afterLogin)/home/page.tsx
> +      authorImage: "/profile-placeholder.png",
미리 아무 이미지나 가지고 오셔서 확인 해보셔도 좋을 것 같아요

2024-11-12 10:55 UTC, merged